name: ECS CI/CD

on:
  push:
    branches: ["main"]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup latest bun
      - name: Setup Bun Latest
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Clean install the dependencies
      - name: Installing Dependencies
        run: bun install --frozen-lockfile

      # Run linting
      - name: Lint
        run: bun run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup latest bun
      - name: Setup Bun Latest
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Clean install the dependencies
      - name: Installing Dependencies
        run: bun install --frozen-lockfile

      # Run Tests
      - name: Run Tests
        run: bun run test
